import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });
  console.log(hello.data);

  return (
    <>
      <Head>
        <title>Create T3 blog</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-gradient-to-b from-[#2e026d] to-[#15162c] py-12 text-white">
        <div className="container mx-auto px-4">
          <h1 className="text-center text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="text-[hsl(280,100%,70%)]">T3</span> App Blog
          </h1>
          <div className="mt-10 grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
            <Link href="https://create.t3.gg/en/usage/first-steps">
              <div className="rounded-xl bg-white/10 p-6">
                <h3 className="mb-4 text-2xl font-bold">Blog Title</h3>
                <div className="mb-4">Blog Description</div>
                <span className="text-base text-gray-400">2023/12/03</span>
              </div>
            </Link>
            <Link href="https://create.t3.gg/en/usage/first-steps">
              <div className="rounded-xl bg-white/10 p-6">
                <h3 className="mb-4 text-2xl font-bold">Blog Title</h3>
                <div className="mb-4">Blog Description</div>
                <span className="text-base text-gray-400">2023/12/03</span>
              </div>
            </Link>
            <Link href="https://create.t3.gg/en/usage/first-steps">
              <div className="rounded-xl bg-white/10 p-6">
                <h3 className="mb-4 text-2xl font-bold">Blog Title</h3>
                <div className="mb-4">Blog Description</div>
                <span className="text-base text-gray-400">2023/12/03</span>
              </div>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
