-- CreateTable
CREATE TABLE "Post" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "title" TEXT NOT NULL,
    "descriprion" TEXT,
    "createdeAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
